### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by coderschoolreview** [coder-superteam/FinalProject#1]
Dear team, congrats on getting together and agreeing on a feasible idea. Thanks for the submission. It sounds like a fun app; is it like a StackOverflow for English translation?

Haha, sorry we should have been clearer. Ideally you can use the GIF to show us your mockups. You can upload your mockup images to invisionapp and add interaction to them, then show off via a GIF. See [this example](http://i.imgur.com/PykwgZt.gif) by another group in your class. Currently we'd have to click on each png file in your wireframe folder :)

Suggestions:

- Could you share your survey results with me via our group slack channel? What did you learn from it? How will you get your first 10 users?
- Can you share your schema? This is required in Milestone 1 as well.
- What apps that are similar to your idea that inspire you? For example, check out http://lang-8.com/ -- a place where I can help you learn my native tongue and vice versa. Duolingo app is another: it takes advantage of the power of crowd sourced translation to build great learning content.
- Are there good English learning or English translator communities that will immediately love an app like yours?
- Try to use "believable looking" fake data, not just "lorem ipset" everywhere. For example, I don't understand your chatbot mockup. It's useful to think about fake data early on so that it's easier to figure out UI UX and to explain the use case.

Look forward to your updates.

**Comment by hnanhquoc** [comment]
Hi @coderschoolreview 
Thanks a lot for your review, we did not do a good job last week, so we're trying to fix them all. Please help us review some updates: 

- Could you share your survey results with me via our group slack channel? -> Yes, please find it at [here](https://docs.google.com/spreadsheets/d/1tGUtyS306tZxQBhFdYkmQ_xMMby5Orut2wAF0pB4__c/edit?usp=sharing). The most valuable thing we can get from it is users, especially in VN, are not satisfied with all these tools. For example, they love GG Translate for its clean form and convenient while other tools  for their performance and accuracy.
- Can you share your schema? -> We add to **db/schema.rb** file as well as **erd.pdf**, please help us take a look.
- What apps that are similar to your idea that inspire you? -> Thanks for your ideas, we did learn from these site and improved our app in a better way. For example, comparing to HiNative, we find some cons: no search, support from Vietnamese community is not good enough, and user must signup (sometime, like GG Translate, they just want to get the result in the fastest way). We also learn from HiNative that it supports a clean formatted with audio support.
- Are there good English learning or English translator communities that will immediately love an app like yours? -> Our survey members is not large enough to conclude this, but based on what they said, who don't want an app that's as convenient as GG Translator and powerful as StackOverflow?
- Try to use "believable looking" fake data -> we add wireframe.gif.
